apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # base64 encoded username generated earlier
  mongo-user: bW9uZ291c2Vy
  # base64 password generated earlier
  mongo-password: bW9uZ29wYXNzd29yZA==
